name: (Gaudi2) Non-regression tests

on:
  pull_request_review:
    types: [submitted]

concurrency:
  group: ${{ github.workflow }}

jobs:
  stable-diffusion:
    name: Test Stable Diffusion
    if: github.event.review.state == 'approved'
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull image
        run: |
          docker pull vault.habana.ai/gaudi-docker/1.14.0/ubuntu22.04/habanalabs/pytorch-installer-2.1.1:latest
      - name: Run tests
        run: |
          docker run \
            -v $PWD:/root/workspace \
            --workdir=/root/workspace \
            --runtime=habana \
            -e HABANA_VISIBLE_DEVICES=all \
            -e OMPI_MCA_btl_vader_single_copy_mechanism=none \
            -e GAUDI2_CI=1 \
            -e HTTP_PROXY=http://proxy-chain.intel.com:911 \
            -e HTTPS_PROXY=http://proxy-chain.intel.com:912 \
            --cap-add=sys_nice \
            --net=host \
            --ipc=host \
            vault.habana.ai/gaudi-docker/1.14.0/ubuntu22.04/habanalabs/pytorch-installer-2.1.1:latest \
            /bin/bash tests/ci/slow_tests_diffusers.sh

